project:
  type: website

website:
  page-navigation: true
  title: "NOAA quarto simple"
  site-url: "https://mikewessel.github.io/NOAA-Culebra-LBSP"
  repo-url: "https://github.com/mikewessel/NOAA-Culebra-LBSP"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "NMFS OpenSci"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Data Entry Portal
      - href: content/Near.Rmd
        text: Nearshore Data Entry
      - href: content/Watershed.Rmd
        text: Watershed Data Entry
      - href: content/Nearshore-Datachecks.Rmd
        text: Data Checks - Nearshore Field
      - href: content/watershed_fld.Rmd
        text: Data Checks - Watershed Field
      - href: content/watershed-lab2.Rmd
        text: Data Checks - Watershed Lab

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto


