---
title: "Culebra LBSP"
subtitle: "Data entry portal for water quality sampling"
page-layout: full
---

This site provides links and instructions for using google forms to enter water quality data for both the "Nearshore" and "Watershed" components of NOAA's Ridge to Reef monitoring program in Culebra, Puerto Rico. 

## Instructions

* Step 1: Print datasheets for sampling each month. The file in the link provided at the end of this paragraph contains datasheets for both the sonde measurements as well and the laboratory nutrients and bacteriological sampling. 

There are 8 sites in the Watershed sampling components that are to be sampled monthly so print 8 datasheets using the following link [Watershed Datasheets](https://docs.google.com/document/d/17oZ_msC6d49UCro2x92w2r4P4DCnu0YX/edit)

There are 13 sites in the Nearshore sampling components that are to be sampled monthly so print 13 datasheets using the following link [Nearshore Datasheets](https://docs.google.com/document/d/1blpa4Iob9zMFprBdBVjw-C5EYTtMRYO7/edit)

* Step 2: Collect samples and record information on datasheets. Be sure to have a cooler with ice and place all water samples (both nutrients and bacterial samples) on ice. Write site anme (or abbreviation), date and time on collected water samples. Eureka Sonde samples should be measured in the watercourse if possible, and if not, in a large plastic bucket. Be sure to rinse equipment after each sample with DI water. Consult workplans in the following folder for more detailed instructions on sample collection [Work Plans](https://drive.google.com/drive/u/1/folders/1Jfijtywj3ZfLIrinoLc9D4M8A9y6mx2z)

* Step 3: Process Nutrient and Bacteriological samples

* Step 4: Enter datausing this data entry portal. Te tabs on the left contain links to Google Forms that should be used for entering data. Do not use the spreadsheets to enter data, use the Google Forms. The spreadhseet links should be used only to check that the data are entered correctly and to correct any errors. 



