---
title: "Watershed_Lab_Data_Checks"
author: "Mwessel"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)

```



```{r mani}

library(googlesheets4)
library(googledrive)
library(ggplot2)
library(dplyr)
library(psych)
library(tidyverse)
library(rlang)
library(knitr)
library(lubridate)
library(kableExtra)
library(forcats)
library(reshape2)

# read in googlesheet
doit<-data.frame(read_sheet("https://docs.google.com/spreadsheets/d/1qWWiaY-w2_Z-NJINq-mnOCpXk_fTmuQxA0sgXArYbgg/edit?usp=sharing"))

#s.data.frame(doit)
#names(doit)

#rename variables and calculate KdPar

doit2<-doit%>%
rename(
 Site.ID = Sample.ID,  
 Monochlorine.mgl = Monochorine..mg.l.  ,        
 NH4.mgl = Total.Ammonium..NH4.mg.l.  ,          
 NO3.mgl = Nitrate..NO3.mg.l. ,                  
 TN.mgl = Total.Nitrogen...TN.mg.l.,             
 Flow.gsec  = Flow..gal.sec. ,                   
 Ecoli.100ml = Escherichia..Coli..100ml.,        
 Date = Date.of.Monitoring,                      
 NO2.mgl = Nitrite...NO2.mg.l.,                  
 NH3.mgl = Free.Ammonia..NH3.mg.l.,              
 OP.mgl = Orthophosphate..OP.mg.l.,              
 TKN.mgl = Total.Kjeldahl.Nitrogen..TKN.mg.l.,   
 Fcoli.100ml = Fecal.Coliform..100ml.                  
  )%>%
mutate(Hr=hour(Time),Hour=hour(Time),Minute=minute(Time),Month=month(Date),Year=year(Date))%>%
unite(Time, Hr,Minute, sep = ":")

# only pull the latest month for summary - this will work unless there is a sampling event that crosses a month
doit2<-doit2%>%
 mutate(mxmn=max(Month),mxyr=max(Year))%>%
  filter(Year==mxyr & Month==mxmn)
labelit<-paste(max(doit2$Year),"-",max(doit2$Month))
```


Descriptive Statistics For Latest Sampling Event


```{r summit}



#| warning: false
#for some reason the names are a list even though its a dataframe so you have to unlist it;

varit<- c('Monochlorine.mgl','NH4.mgl','NO3.mgl','TN.mgl','Flow.gsec','Ecoli.100ml','Hour','NO2.mgl','NH3.mgl','OP.mgl','TKN.mgl','Fcoli.100ml')

df2 <- as.data.frame(lapply(doit2, unlist))
df2<-df2%>%
  mutate(across(all_of(varit), ~gsub(">", "", .)))%>%
 mutate(across(all_of(varit),as.numeric))
#sapply(df2,class)

# try and pull qualifiers from fields


#qual<-df2%>% 
#mutate(across(all_of(varit), ~gsub(">", "", .)))%>%
#mutate(across(all_of(varit),as.numeric))%>%  
#mutate_at(c('Monochlorine.mgl','NH4.mgl','NO3.mgl','TN.mgl','Flow.gsec','Ecoli.100ml','#Hour','NO2.mgl','NH3.mgl','OP.mgl','TKN.mgl','Fcoli.100ml'), as.numeric)%>% 
#   describe(quant=c(.25,.75),na.rm =TRUE,check=TRUE,omit=FALSE) %>%
#    as_tibble(rownames="Param")%>%
#  select(Param,n,mean,sd,min,median,max)%>%
#  kbl(digits=3, caption = paste0(labelit))%>%
#  kable_styling()
#sumvars
#max(doit2$TN.mgl)
#sapply(qual,class)




# Make a table -anything that had a > gets excluded for some reason
options(scipen=999)
sumvars <- df2 %>%
   select(
Monochlorine.mgl,NH4.mgl,NO3.mgl,TN.mgl,Flow.gsec,Ecoli.100ml,Hour,NO2.mgl,NH3.mgl,OP.mgl,TKN.mgl,Fcoli.100ml
)%>%
#mutate_at(c('Monochlorine.mgl','NH4.mgl','NO3.mgl','TN.mgl','Flow.gsec','Ecoli.100ml','#Hour','NO2.mgl','NH3.mgl','OP.mgl','TKN.mgl','Fcoli.100ml'), as.numeric)%>% 
   describe(quant=c(.25,.75),na.rm =TRUE) %>%
    as_tibble(rownames="Param")%>%
  select(Param,n,mean,sd,min,median,max)%>%
  kbl(digits=3, caption = paste0(labelit))%>%
  kable_styling()
sumvars


```



Watershed Nutrient Plot

##  Nitrogen Constituents by Site
```{r plotit}

#values - not drawing line

plotit<-doit2 %>%
 mutate_at(c('Monochlorine.mgl','NH4.mgl','NO3.mgl','TN.mgl','Flow.gsec','Ecoli.100ml','Hour','NO2.mgl','NH3.mgl','OP.mgl','TKN.mgl','Fcoli.100ml'), as.numeric)%>%
  pivot_longer(
    cols = c(TN.mgl,NO3.mgl,NO2.mgl,TKN.mgl),
    names_to = "Param",
    values_to = "Conc"
  )%>%
 
#Reorder for plot
 mutate(name = factor(Site.ID, levels=c("Old Man Plaza", "AeropuertoY", "Plant", "P3_out", "P4_out","Bridge", "Turtle Stream", "Coronel Pond")))
         
 
Nuts<-ggplot(plotit, aes(x=name,y=Conc,fill=Param))+
geom_bar(position = "dodge",stat="identity")+
ylab("Concentration (mg/l)") +xlab("Site")+
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,),
      axis.title.y.left = element_text(colour = "black"),
  #    axis.title.y.right = element_text(colour = "red"),
      )
Nuts

```

Fecal Coliform Plot

```{r plotit2}

plotit2<-doit2 %>%
   mutate_at(c('Ecoli.100ml','Fcoli.100ml'), as.numeric)%>%
    select(Site.ID,Ecoli.100ml, Fcoli.100ml)%>%
  pivot_longer(
    cols = c(Ecoli.100ml, Fcoli.100ml),
    names_to = "Parm",
    values_to = "Conc"
  )%>%
#Reorder for plot
 mutate(name = factor(Site.ID, levels=c("Old Man Plaza", "AeropuertoY", "Plant", "P3_out", "P4_out","Bridge", "Turtle Stream", "Coronel Pond")),Conc2=as.numeric(Conc))

Nuts2<-ggplot(plotit2, aes(x=name,y=Conc2,fill=Parm))+
geom_bar(position = "dodge",stat="identity")+
ylab("Counts (MPN/100ml)") +xlab("Site") +
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
      axis.title.y.left = element_text(colour = "black"),
  #    axis.title.y.right = element_text(colour = "red"),
      )
Nuts2

```



